<a href="https://colab.research.google.com/github/Davron030901/Machine_Learning/blob/main/3_interactive_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 My NLP Lab: Words into Numbers!

Hi! 👋 Welcome to your hands-on lab. 🎉
Here you will type your OWN sentence and watch the math happen! ✨

We use two tools:
- 🔢 **NumPy** = the number helper
- 📊 **pandas** = the table helper

Just press **Shift + Enter** on each box to run it. Let's go! 🚀

## Step 1: Get Our Tools 🛠️

First we grab NumPy and pandas. 🔢📊
Run this box first! 👇

In [9]:
import numpy as np
import pandas as pd

print("Tools ready! 🎉")
print("NumPy and pandas are awake. 🔢📊")

Tools ready! 🎉
NumPy and pandas are awake. 🔢📊

## Step 2: Our Tiny Word List (Vocabulary) 📒

The computer can't read words. Only numbers! 🔢
So we make a small word list. Each word gets a slot. 🎰

Our 5 words: **i, love, hate, pizza, you**
- Slot 0 = i
- Slot 1 = love
- Slot 2 = hate
- Slot 3 = pizza
- Slot 4 = you

In [10]:
# Our tiny vocabulary (word list) 📒
vocab = ["i", "love", "hate", "pizza", "you"]

# Show it as a nice pandas table 📊
vocab_table = pd.DataFrame({"slot": range(len(vocab)), "word": vocab})
print("Our word list: 📒")
vocab_table

Our word list: 📒

   slot   word
0     0      i
1     1   love
2     2   hate
3     3  pizza
4     4    you

## Step 3: YOU Type a Sentence! ✍️

Now the fun part. Type your OWN sentence! 🎉
Try something like: **i love pizza** 🍕

We will chop it into pieces (tokens). ✂️
Then turn it into a tiny number array with NumPy. 🔢

👉 Use only words from our list (i, love, hate, pizza, you) for the best result!

In [12]:
# Type your sentence here! ✍️
sentence = input("Type a sentence (try 'i love pizza'): ")

# Step A: chop into tokens (lowercase + split by space) ✂️
tokens = sentence.lower().split()
print("Your tokens: ✂️", tokens)

# Step B: turn into numbers with NumPy 🔢
# 1 = the word is here, 0 = the word is NOT here
vector = np.zeros(len(vocab), dtype="float32")  # start with all zeros

for word in tokens:
    if word in vocab:
        slot = vocab.index(word)   # find the word's slot
        vector[slot] = 1           # mark it with a 1 ✅
    else:
        print(f"'{word}' is not in our list. Skipping it! 👻")

print("Your number array: 🔢", vector)

Type a sentence (try 'i love pizza'): I love
Your tokens: ✂️ ['i', 'love']
Your number array: 🔢 [1. 1. 0. 0. 0.]

## Step 4: See Your Numbers in a Table 📊

Let's look at your sentence as a pandas table.
**1** means the word is in your sentence. ✅
**0** means it is not. ❌

In [13]:
# Show the vector next to each word 📊
result = pd.DataFrame({
    "word": vocab,
    "in_your_sentence": vector.astype(int)
})
result

    word  in_your_sentence
0      i                 1
1   love                 1
2   hate                 0
3  pizza                 0
4    you                 0

## Step 5: Add Weights (Importance Points) ⭐

Now we give each word an importance point (a weight).
Happy words get **+** points. Sad words get **−** points.

- love → **+3** 😄
- pizza → **+1** 🍕
- hate → **−3** 😢
- i → **0** (boring) 😴
- you → **0** (boring) 😴

We multiply your sentence by these weights, then ADD them up! ➕

In [14]:
# Importance points (weights) for each slot ⭐
# order: i, love, hate, pizza, you
weights = np.array([0, 3, -3, 1, 0], dtype="float32")

# Multiply each word by its weight, then add them all up ➕
score = np.sum(vector * weights)

print("Weights:        ⭐", weights)
print("Your sentence:  🔢", vector)
print("---------------------------------")
print("Final score (added up): 🎯", score)

Weights:        ⭐ [ 0.  3. -3.  1.  0.]
Your sentence:  🔢 [1. 1. 0. 0. 0.]
---------------------------------
Final score (added up): 🎯 3.0

## Step 6: The ReLU Gate ⚡

Remember ReLU?
Rule: if the number is negative → make it **0**. If positive → keep it! ⚡

Let's send your score through the ReLU gate. 🚪

In [18]:
# The ReLU gate as a tiny function ⚡
def relu(x):
    return max(0, x)   # negative becomes 0, positive stays

gate_output = relu(score)

print("Score before gate: 🎯", score)
print("Score after ReLU:  ⚡", gate_output)

if gate_output > 0:
    print("The gate is OPEN! This feels HAPPY! 😄")
else:
    print("The gate is CLOSED (0). This feels SAD! 😢")

Score before gate: 🎯 3.0
Score after ReLU:  ⚡ 3.0
The gate is OPEN! This feels HAPPY! 😄

## Step 7: The "Oops" Score (Loss) 😬

Now let's check: how wrong was the brain?
You tell it the RIGHT answer. Then we measure the mistake. 📏

- Type **1** if your sentence is really happy 😄
- Type **0** if your sentence is really sad 😢

Oops score = (right answer − guess) squared.
Squared just means "multiply by itself" so it is never negative. 🔢
Small Oops = good! Big Oops = bad! 📉

In [19]:
# What is the TRUE answer? You decide! 🎯
right_answer = float(input("Is your sentence happy (1) or sad (0)? Type 1 or 0: "))

# Turn the gate output into a simple guess between 0 and 1
# (we just cap it at 1 to keep it tiny and simple) 🧸
guess = min(gate_output, 1)

# Oops score = (right - guess) squared 😬
oops = (right_answer - guess) ** 2

print("Right answer: 🎯", right_answer)
print("Brain guess:  🤔", guess)
print("---------------------------------")
print("Oops score: 😬", oops)

if oops < 0.5:
    print("Tiny Oops! The brain did GREAT! 🎉")
else:
    print("Big Oops! The brain needs more practice. 💪")

Is your sentence happy (1) or sad (0)? Type 1 or 0: 1
Right answer: 🎯 1.0
Brain guess:  🤔 1
---------------------------------
Oops score: 😬 0.0
Tiny Oops! The brain did GREAT! 🎉

## Step 8: Try Many Sentences! 🔁

Let's test a few sentences at once and put them in a table. 📊
This shows how different words change the score! 🎢

You don't type here — just run it and look! 👀

In [20]:
# A few test sentences to compare 🧪
tests = ["i love pizza", "i hate pizza", "i love you", "i hate you"]

rows = []
for s in tests:
    toks = s.lower().split()
    v = np.zeros(len(vocab), dtype="float32")
    for w in toks:
        if w in vocab:
            v[vocab.index(w)] = 1
    sc = np.sum(v * weights)       # add up the weights
    out = relu(sc)                 # ReLU gate
    feeling = "HAPPY 😄" if out > 0 else "SAD 😢"
    rows.append({"sentence": s, "score": sc, "after_relu": out, "feeling": feeling})

# Show everything in a neat pandas table 📊
table = pd.DataFrame(rows)
table

       sentence  score  after_relu  feeling
0  i love pizza    4.0         4.0  HAPPY 😄
1  i hate pizza   -2.0         0.0    SAD 😢
2    i love you    3.0         3.0  HAPPY 😄
3    i hate you   -3.0         0.0    SAD 😢

## 🏆 You Did It!

Look what you just built with NumPy and pandas: 🎉
- ✂️ Chopped a sentence into tokens
- 🔢 Turned words into a number array
- ⭐ Added importance weights
- ⚡ Ran it through a ReLU gate
- 😬 Measured the "Oops" score

This is the REAL math inside big AIs, just tiny! 🧠💪
Try changing the **weights** in Step 5 and run again. What happens? 🤔✨